server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.73.102:1111


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)，这个在controller引入
service-url:
  nacos-user-service: http://nacos-payment-provider


